spring:
  mvc:
    cors:
      mappings:
        "/**":
          allowed-origins: "http://localhost:4200"
          allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
          allowed-headers: "*"
          allow-credentials: true